export const COUNTRIES: { label: string; value: string }[] = [
  { label: "Afganistán", value: "Afganistán" },
  { label: "Albania", value: "Albania" },
  { label: "Alemania", value: "Alemania" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Antigua y Barbuda", value: "Antigua y Barbuda" },
  { label: "Arabia Saudita", value: "Arabia Saudita" },
  { label: "Argelia", value: "Argelia" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaiyán", value: "Azerbaiyán" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bangladés", value: "Bangladés" },
  { label: "Barbados", value: "Barbados" },
  { label: "Baréin", value: "Baréin" },
  { label: "Bélgica", value: "Bélgica" },
  { label: "Belice", value: "Belice" },
  { label: "Benín", value: "Benín" },
  { label: "Bielorrusia", value: "Bielorrusia" },
  { label: "Birmania", value: "Birmania" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia y Herzegovina", value: "Bosnia y Herzegovina" },
  { label: "Botsuana", value: "Botsuana" },
  { label: "Brasil", value: "Brasil" },
  { label: "Brunéi", value: "Brunéi" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Bután", value: "Bután" },
  { label: "Cabo Verde", value: "Cabo Verde" },
  { label: "Camboya", value: "Camboya" },
  { label: "Camerún", value: "Camerún" },
  { label: "Canadá", value: "Canadá" },
  { label: "Catar", value: "Catar" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Chipre", value: "Chipre" },
  { label: "Ciudad del Vaticano", value: "Ciudad del Vaticano" },
  { label: "Colombia", value: "Colombia" },
  { label: "Comoras", value: "Comoras" },
  { label: "Corea del Norte", value: "Corea del Norte" },
  { label: "Corea del Sur", value: "Corea del Sur" },
  { label: "Costa de Marfil", value: "Costa de Marfil" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croacia", value: "Croacia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Dinamarca", value: "Dinamarca" },
  { label: "Dominica", value: "Dominica" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Egipto", value: "Egipto" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Emiratos Árabes Unidos", value: "Emiratos Árabes Unidos" },
  { label: "Eritrea", value: "Eritrea" },
  { label: "Eslovaquia", value: "Eslovaquia" },
  { label: "Eslovenia", value: "Eslovenia" },
  { label: "España", value: "España" },
  { label: "Estados Unidos", value: "Estados Unidos" },
  { label: "Estonia", value: "Estonia" },
  { label: "Esuatini", value: "Esuatini" },
  { label: "Etiopía", value: "Etiopía" },
  { label: "Filipinas", value: "Filipinas" },
  { label: "Finlandia", value: "Finlandia" },
  { label: "Fiyi", value: "Fiyi" },
  { label: "Francia", value: "Francia" },
  { label: "Gabón", value: "Gabón" },
  { label: "Gambia", value: "Gambia" },
  { label: "Georgia", value: "Georgia" },
  { label: "Ghana", value: "Ghana" },
  { label: "Granada", value: "Granada" },
  { label: "Grecia", value: "Grecia" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guyana", value: "Guyana" },
  { label: "Guinea", value: "Guinea" },
  { label: "Guinea-Bisáu", value: "Guinea-Bisáu" },
  { label: "Guinea Ecuatorial", value: "Guinea Ecuatorial" },
  { label: "Haití", value: "Haití" },
  { label: "Hungría", value: "Hungría" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Irak", value: "Irak" },
  { label: "Irán", value: "Irán" },
  { label: "Irlanda", value: "Irlanda" },
  { label: "Islandia", value: "Islandia" },
  { label: "Islas Marshall", value: "Islas Marshall" },
  { label: "Islas Salomón", value: "Islas Salomón" },
  { label: "Israel", value: "Israel" },
  { label: "Italia", value: "Italia" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japón", value: "Japón" },
  { label: "Jordania", value: "Jordania" },
  { label: "Kazajistán", value: "Kazajistán" },
  { label: "Kenia", value: "Kenia" },
  { label: "Kirguistán", value: "Kirguistán" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Laos", value: "Laos" },
  { label: "Lesoto", value: "Lesoto" },
  { label: "Letonia", value: "Letonia" },
  { label: "Líbano", value: "Líbano" },
  { label: "Liberia", value: "Liberia" },
  { label: "Libia", value: "Libia" },
  { label: "Liechtenstein", value: "Liechtenstein" },
  { label: "Lituania", value: "Lituania" },
  { label: "Luxemburgo", value: "Luxemburgo" },
  { label: "Macedonia del Norte", value: "Macedonia del Norte" },
  { label: "Madagascar", value: "Madagascar" },
  { label: "Malasia", value: "Malasia" },
  { label: "Malaui", value: "Malaui" },
  { label: "Maldivas", value: "Maldivas" },
  { label: "Malí", value: "Malí" },
  { label: "Malta", value: "Malta" },
  { label: "Marruecos", value: "Marruecos" },
  { label: "Mauricio", value: "Mauricio" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "México", value: "México" },
  { label: "Micronesia", value: "Micronesia" },
  { label: "Moldavia", value: "Moldavia" },
  { label: "Mónaco", value: "Mónaco" },
  { label: "Mongolia", value: "Mongolia" },
  { label: "Montenegro", value: "Montenegro" },
  { label: "Mozambique", value: "Mozambique" },
  { label: "Namibia", value: "Namibia" },
  { label: "Nauru", value: "Nauru" },
  { label: "Nepal", value: "Nepal" },
  { label: "Nicaragua", value: "Nicaragua" },
  { label: "Níger", value: "Níger" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Noruega", value: "Noruega" },
  { label: "Nueva Zelanda", value: "Nueva Zelanda" },
  { label: "Omán", value: "Omán" },
  { label: "Países Bajos", value: "Países Bajos" },
  { label: "Pakistán", value: "Pakistán" },
  { label: "Palaos", value: "Palaos" },
  { label: "Paraguay", value: "Paraguay" },
  { label: "Perú", value: "Perú" },
  { label: "Polonia", value: "Polonia" },
  { label: "Portugal", value: "Portugal" },
  { label: "Reino Unido", value: "Reino Unido" },
  { label: "República Centroafricana", value: "República Centroafricana" },
  { label: "República Checa", value: "República Checa" },
  { label: "República del Congo", value: "República del Congo" },
  {
    label: "República Democrática del Congo",
    value: "República Democrática del Congo",
  },
  { label: "República Dominicana", value: "República Dominicana" },
  { label: "Ruanda", value: "Ruanda" },
  { label: "Rumania", value: "Rumania" },
  { label: "Rusia", value: "Rusia" },
  { label: "Samoa", value: "Samoa" },
  { label: "San Cristóbal y Nieves", value: "San Cristóbal y Nieves" },
  { label: "San Marino", value: "San Marino" },
  {
    label: "San Vicente y las Granadinas",
    value: "San Vicente y las Granadinas",
  },
  { label: "Santa Lucía", value: "Santa Lucía" },
  { label: "Santo Tomé y Príncipe", value: "Santo Tomé y Príncipe" },
  { label: "Senegal", value: "Senegal" },
  { label: "Serbia", value: "Serbia" },
  { label: "Seychelles", value: "Seychelles" },
  { label: "Sierra Leona", value: "Sierra Leona" },
  { label: "Singapur", value: "Singapur" },
  { label: "Siria", value: "Siria" },
  { label: "Somalia", value: "Somalia" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Suazilandia", value: "Suazilandia" },
  { label: "Sudáfrica", value: "Sudáfrica" },
  { label: "Sudán", value: "Sudán" },
  { label: "Sudán del Sur", value: "Sudán del Sur" },
  { label: "Suecia", value: "Suecia" },
  { label: "Suiza", value: "Suiza" },
  { label: "Surinam", value: "Surinam" },
  { label: "Tailandia", value: "Tailandia" },
  { label: "Tanzania", value: "Tanzania" },
  { label: "Tayikistán", value: "Tayikistán" },
  { label: "Timor Oriental", value: "Timor Oriental" },
  { label: "Togo", value: "Togo" },
  { label: "Tonga", value: "Tonga" },
  { label: "Trinidad y Tobago", value: "Trinidad y Tobago" },
  { label: "Túnez", value: "Túnez" },
  { label: "Turkmenistán", value: "Turkmenistán" },
  { label: "Turquía", value: "Turquía" },
  { label: "Tuvalu", value: "Tuvalu" },
  { label: "Ucrania", value: "Ucrania" },
  { label: "Uganda", value: "Uganda" },
  { label: "Uruguay", value: "Uruguay" },
  { label: "Uzbekistán", value: "Uzbekistán" },
  { label: "Vanuatu", value: "Vanuatu" },
  { label: "Venezuela", value: "Venezuela" },
  { label: "Vietnam", value: "Vietnam" },
  { label: "Yemen", value: "Yemen" },
  { label: "Yibuti", value: "Yibuti" },
  { label: "Zambia", value: "Zambia" },
  { label: "Zimbabue", value: "Zimbabue" },
];

export const GENDER: { label: string; value: string }[] = [
  {
    label: "Male",
    value: "Male",
  },
  {
    label: "Female",
    value: "Female",
  },
  {
    label: "Other",
    value: "Other",
  },
];

export const COMPANY_SIZE: { label: string; value: string }[] = [
  {
    label: "1-10",
    value: "1-10",
  },
  {
    label: "11-50",
    value: "11-50",
  },
  {
    label: "51-200",
    value: "51-200",
  },
  {
    label: "201-500",
    value: "201-500",
  },
  {
    label: "500+",
    value: "500+",
  },
];

export const DATA_RADIOS_STEP_THREE: string[] = ["Personal", "Business"];

export const DATA_RADIOS_STEP_FIVE: string[] = [
  "Online Ads",
  "Friend Referral",
  "Social Media",
  "Other",
];

export const DEFAULT_PERSONAL_INFO = {
  full_name: "",
  email: "",
  phone_number: "",
};

export const DEFAULT_ADDRESS_INFO = {
  street_address: "",
  city: "",
  postal_code: "",
  country: "",
};

export const DEFAULT_ACCOUNT_DETAILS = {
  username: "",
  password: "",
  confirm_password: "",
  profile_type: "",
};

export const DEFAULT_ADDITIONAL_PERSONAL_INFO = {
  date_of_birth: "",
  gender: "",
};

export const DEFAULT_BUSINESS_INFO = {
  company_name: "",
  company_size: "",
  role_in_company: "",
};

export const DEFAULT_PREFERENCES = {
  notifications: false,
  how_heard: "",
  terms_agreed: false,
};

export const DEFAULT_PREFERENCES_ERROR = {
  notifications: "",
  how_heard: "",
  terms_agreed: "",
};

const API_BASE_URL = process.env.API_BASE_URL;

const API_V3 = `${API_BASE_URL}/v3/`;
