import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StepsFormProvider } from "@/context/StepsFormProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <StepsFormProvider>{children}</StepsFormProvider>
      </body>
    </html>
  );
}
